# Generated by Django 3.0.6 on 2020-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('1', 'Govt Job'), ('2', 'FPSC'), ('3', 'PPSC'), ('4', 'NTS'), ('5', 'PAK ARMY'), ('6', 'PAK NAVY'), ('7', 'PAK AIR FORCE')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('last_date', models.DateTimeField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=300)),
                ('website', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled', models.BooleanField(default=False)),
                ('salary', models.IntegerField(blank=True, default=0)),
                ('required_exp', models.CharField(choices=[('1', 'None'), ('2', '1 Year'), ('3', '2 Year'), ('4', '3 Year'), ('5', '4 Year'), ('6', '5 Year'), ('7', '6 Year'), ('8', '7 Year'), ('9', '8 Year'), ('10', '9 Year'), ('11', '10 Year')], max_length=50)),
            ],
        ),
    ]
