# Generated by Django 3.0.7 on 2020-06-23 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20200623_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='jobs'),
            preserve_default=False,
        ),
    ]
