# Generated by Django 3.0.7 on 2020-06-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_auto_20200624_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('1', 'Govt Job'), ('2', 'FPSC'), ('3', 'PPSC'), ('4', 'NTS'), ('5', 'PAK ARMY'), ('6', 'PAK NAVY'), ('7', 'PAK AIR FORCE')], max_length=100),
        ),
    ]
