# Generated by Django 3.0.7 on 2020-06-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_auto_20200624_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.IntegerField(choices=[('1', 'Govt Job'), ('2', 'FPSC'), ('3', 'PPSC'), ('4', 'NTS'), ('5', 'PAK ARMY'), ('6', 'PAK NAVY'), ('7', 'PAK AIR FORCE')]),
        ),
    ]
