# Generated by Django 3.0.5 on 2020-06-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_auto_20200630_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('1', 'Govt Job'), ('FPSC', 'FPSC'), ('PPSC', 'PPSC'), ('NTS', 'NTS'), ('5', 'PAK ARMY'), ('6', 'PAK NAVY'), ('7', 'PAK AIR FORCE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='jtype',
            field=models.CharField(choices=[('1', 'Govt Job'), ('FPSC', 'FPSC'), ('PPSC', 'PPSC'), ('NTS', 'NTS'), ('5', 'PAK ARMY'), ('6', 'PAK NAVY'), ('7', 'PAK AIR FORCE')], max_length=10),
        ),
    ]
