# Generated by Django 3.0.5 on 2020-06-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_auto_20200630_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('1', 'Govt Job'), ('2', 'FPSC'), ('3', 'PPSC'), ('4', 'NTS'), ('5', 'PAK ARMY'), ('6', 'PAK NAVY'), ('7', 'PAK AIR FORCE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='jtype',
            field=models.CharField(choices=[('1', 'Govt Job'), ('2', 'FPSC'), ('3', 'PPSC'), ('4', 'NTS'), ('5', 'PAK ARMY'), ('6', 'PAK NAVY'), ('7', 'PAK AIR FORCE')], max_length=10),
        ),
    ]
