# Generated by Django 3.0.5 on 2020-06-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_auto_20200630_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='posts',
        ),
    ]
